[package]
name = "nom_learn"
version = "0.1.2"
edition = "2021"
description = "WhileDB"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
text_io = "0.1.12"